# Generated by Django 5.1.6 on 2025-04-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_precinct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='party',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct',
            field=models.CharField(max_length=2),
        ),
    ]
