# Generated by Django 5.1.6 on 2025-04-17 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pastorder',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.cart'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PastOrderItem',
        ),
    ]
