# Generated by Django 5.1.6 on 2025-04-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_cart_removed_pastorder_cart_delete_pastorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
