# Generated by Django 5.1.6 on 2025-04-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='aisle_distances',
            field=models.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
