# Generated by Django 5.1.6 on 2025-04-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_store_aisle_distances'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastorder',
            name='routes',
            field=models.JSONField(default=dict),
        ),
    ]
