# Generated by Django 5.1.5 on 2025-02-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_alter_statusmessage_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmessage',
            name='timestamp',
        ),
    ]
