# Generated by Django 5.1.6 on 2025-03-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0007_image_statusimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='ImageField',
            new_name='imageField',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Profile',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='TimeStamp',
            new_name='timeStamp',
        ),
        migrations.RenameField(
            model_name='statusimage',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='statusimage',
            old_name='StatusMessage',
            new_name='statusMessage',
        ),
    ]
